#! usr/bin/bash
filenames=('client' 'cs32510.' 'cs32511.' 'cs32512.' 'cs32513.' 'cs32514.' 'cxworks.' 'network.' 'network0.' 'network1.' 'network2.' 'network3.' 'receiver.' 'sender.')

for filename in ${filenames[@]}; do
  if [[ $filename == 'client' ]]; then
    filename=''
  fi
  output=`diff ${filename}client.txt details/${filename}client.txt`
  if [[ -z "$output" ]]; then
    echo "${filename}client.txt matches"
  elif [[ -n "$output" ]]; then
    echo "${filename}client.txt differs, run \"diff ${filename}client.txt details/${filename}client.txt\" to check"
  fi
done