INVALID_IP = "error: server ip invalid, connection refused."
INVALID_PORT = "error: server port invalid, connection refused."
INVALID_USERNAME = "error: username has wrong format, connection refused."
USER_ALREADY_LOGGED_IN = "username illegal, connection refused."
WRONG_PARAMS = "error: args should contain <ServerIP> <ServerPort> <Username>"
MSG_TOO_LONG = "message length illegal, connection refused."
EMPTY_MSG = "message format illegal."
ILLEGAL_HASHTAG = "hashtag illegal format, connection refused."
MAX_HASHTAGS= "operation failed: sub %s failed, already exists or exceeds 3 limitation"

LOGIN_SUCCESS = "username legal, connection established."
EXIT_SUCCESS = "bye bye"
SUB_OR_UNSUB_SUCCESS = "operation success"

SUB_OR_UNSUB_ERROR = "INVALID HASHTAG"
MSG_UPLOAD = "UPLOAD"
MSG_DOWNLOAD = "DOWNLOAD"
INVALID_MODE = "INVALID MODE"
